---
name: Test
on:
  push:
jobs:
  job1:
    concurrency:
      group: ${{ github.workflow }}-job1
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go version
      - run: sleep 30
  job2:
    needs: job1
    concurrency:
      group: ${{ github.workflow }}-job2
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: sleep 30
