---
name: Test
on:
  push:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go version
      - run: sleep 30
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: sleep 30
